### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by ruudboon**
Use NPM package to prevent local git requirement for using this package.

### CODE REVIEW

**Comment by ItsEcholot** [comment]
I can’t remember why I chose the git package instead of a NPM one, had to have a reason though. Did you test this, does everything work as expected?

**Comment by wotipka** [comment]
Could this be the reason that the node crashes node-red service?  Latest versions as of this date.  Installed both snmpjs (via command line) and momentum (via pallet).  Whenever I try to deploy this node, node-red crashes and does not restart.  Must remove the snmptrap package from the node_modules directory and restart and everything is fine.

**Comment by ItsEcholot** [comment]
> Could this be the reason that the node crashes node-red service? Latest versions as of this date. Installed both snmpjs (via command line) and momentum (via pallet). Whenever I try to deploy this node, node-red crashes and does not restart. Must remove the snmptrap package from the node_modules directory and restart and everything is fine.

Most likely not take a look at issue #4 . If that doesn‘t help create an issue with your logs attached so I can help you.

**Comment by wotipka** [comment]
I will look into this. Node-red in this instance is running as user pi.  Just to be clear on my end, deploying the snmp trap listen node is what is crashing (I say crashing, node red stops responding) node-red because of permission issues related to the low port?  I will reinstall the node and try to give it a higher port value and see what happens on the deploy.  Thank you in advance for your followup.

kw

**Comment by ItsEcholot** [comment]
Yep that is probably what is happening. To bind to ports lower than 1024 on Linux systems you [have to have root access](https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html).

**Comment by ItsEcholot** [comment]
Using git enables us to use a less outdated version, which isn't published to NPM (yet).

**Pull request closed without merging**
